version: '3.8'

services:
  neo4j:
    image: neo4j:5.13
    container_name: graphsql-neo4j
    environment:
      - NEO4J_AUTH=neo4j/password123
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - graphsql-network

  backend:
    build: ./backend
    container_name: graphsql-backend
    environment:
      - NODE_ENV=production
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password123
    ports:
      - "3000:3000"
    depends_on:
      - neo4j
    networks:
      - graphsql-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: graphsql-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:3000
    depends_on:
      - backend
    networks:
      - graphsql-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:

networks:
  graphsql-network:
    driver: bridge